webhook:
  enabled: false
  url: "INSERT_WEBHOOK_URL"
  avatar-api: "https://minotar.net/avatar/%player%.png"

crate-open-delay: 20
roulette-animation: true

rewards:
  - id: "1"
    amount: 5
    weight: 5
    tier: COMMON

  - id: "2"
    amount: 4
    weight: 4
    tier: UNCOMMON

  - id: "3"
    amount: 3
    weight: 3
    tier: RARE

  - id: "4"
    amount: 2
    weight: 2
    tier: EPIC

  - id: "5"
    amount: 1
    weight: 1
    tier: LEGENDARY
